# Generated by Django 5.2.7 on 2025-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField(blank=True)),
                ('first_name', models.TextField(blank=True)),
                ('res_street_number', models.CharField(blank=True, max_length=16)),
                ('res_street_name', models.TextField(blank=True)),
                ('res_apartment', models.CharField(blank=True, max_length=32)),
                ('res_zip', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('party', models.CharField(blank=True, max_length=2)),
                ('precinct', models.CharField(blank=True, max_length=8)),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
                ('voter_score', models.IntegerField(default=0)),
            ],
        ),
    ]
