# Generated by Django 5.2.6 on 2025-10-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='res_street_name',
            new_name='address_street_name',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='date_of_birth',
            new_name='date_birth',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='date_of_registration',
            new_name='date_registration',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='precinct',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='res_apartment',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='res_street_number',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='res_zip',
        ),
        migrations.AddField(
            model_name='voter',
            name='address_apartment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='address_street_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='address_zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v20state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21primary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21town',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22general',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23town',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
