# Generated by Django 5.2.6 on 2025-10-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_rename_res_street_name_voter_address_street_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='address_apartment_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_street_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
