# Generated by Django 5.2.6 on 2025-10-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_photo_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_field',
            new_name='image_file',
        ),
    ]
