# Generated by Django 5.2.7 on 2025-11-24 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform_handle', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('objective', models.CharField(choices=[('AWARENESS', 'Brand awareness'), ('TRAFFIC', 'Website traffic'), ('ENGAGEMENT', 'Engagement'), ('LEADS', 'Lead generation')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='project.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('content_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('REEL', 'Reel'), ('STORY', 'Story'), ('CAROUSEL', 'Carousel')], max_length=20)),
                ('caption', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='project.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='PostMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='project.post')),
            ],
        ),
    ]
